spring:
# DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hh
    username: "root"
    password: "123456"

  session:
      timeout: 86400

server:
  address: 0.0.0.0


